#!/bin/sh

set -e

ECHO=/bin/echo

EXPORT_LIB=`cat <<-EOF
services/lib
platform/lib
EOF
`

EXPORT_FILE_DIR=`cat <<-EOF
.gitignore
Makefile
apps
config/Makefile
config/common.mk
config/_default_cfg_src_
config/best1101_e
config/2300_codec
config/programmer
mbed
platform/hal
platform/main
rtos
scripts
EOF
`

USAGE="
Usage:
	`basename $0` <to_file> [ <version> [ <git-archive options> ] ]

Description:
	<to_file>	Output file name
	<version>	<tree-ish> - Contents in the <tree-ish>
			WORKING - Contents in working tree
	<git-archive options>	Other options for git-archive

Additional options (can be put out of order):
	L=lib1,...	More library files (comma separated) to pack
	F=file1,...	More files or directories (comma separated) to pack
"

ALL_OPTS="$@"

FILTERED_OPTS=
for opt in $ALL_OPTS; do
	case "$opt" in
		L=*) eval $opt ;;
		F=*) eval $opt ;;
		*) FILTERED_OPTS="$FILTERED_OPTS $opt" ;;
	esac
done

set -- $FILTERED_OPTS

if [ "x$1" = "x" ]; then
	$ECHO -e "$USAGE"
	exit 1
fi
case "$1" in
	*.tar.gz) DEST=$1 ;;
	*) DEST=${1}.tar.gz ;;
esac
shift

if [ "x$1" = "x" ]; then
	VER=HEAD
else
	VER=$1
	shift
fi

L=`$ECHO $L | sed 's/,/ /g'`
F=`$ECHO $F | sed 's/,/ /g'`

$ECHO -e "Packing source files ..."

REAL_EXPORT_FILE_DIR=
for f in $EXPORT_FILE_DIR $F; do
	commented=0
	case "$f" in
		\#*) commented=1 ;;
	esac
	if [ "x$commented" = "x1" ]; then
		$ECHO -en "    Skipping " && ($ECHO -e "$f" | sed 's/^#//')
	elif [ -d $f ] || [ -f $f ]; then
		REAL_EXPORT_FILE_DIR="$REAL_EXPORT_FILE_DIR $f"
	else
		$ECHO -e "    Warning: Missing $f"
	fi
done

if [ "x$REAL_EXPORT_FILE_DIR" = x ]; then
	$ECHO -e "Error: No files or directories found"
	exit 2
fi

ARCH_DEST=${DEST}_tar
if [ "x$VER" = "xWORKING" ]; then
	tar -cf $ARCH_DEST $REAL_EXPORT_FILE_DIR
else
	git archive --format=tar "$@" -o $ARCH_DEST $VER $REAL_EXPORT_FILE_DIR
fi

$ECHO -e "Packing library files ..."

REAL_EXPORT_LIB=
for f in $EXPORT_LIB $L; do
	commented=0
	case "$f" in
		\#*) commented=1 ;;
	esac
	if [ "x$commented" = "x1" ]; then
		$ECHO -en "    Skipping " && ($ECHO -e "$f" | sed 's/^#//')
	elif [ -d $f ] || [ -f $f ]; then
		REAL_EXPORT_LIB="$REAL_EXPORT_LIB $f"
	else
		$ECHO -e "    Warning: Missing $f"
	fi
done

if [ "x$REAL_EXPORT_LIB" != "x" ]; then
	tar -rf $ARCH_DEST $REAL_EXPORT_LIB
fi

cat $ARCH_DEST | gzip -c > $DEST
rm $ARCH_DEST
$ECHO -e "Done."

